### ISSUE TITLE
Images of the cards are not showing.

### ISSUE THREAD

**Issue by prithvi60** [mayankshubham/memory-card-game#1]
![Screenshot (3)](https://user-images.githubusercontent.com/51085756/113983904-1fa72300-9868-11eb-986b-17313b5d622c.png)

Just checked out your repos, good stuff. Thought of letting you know.

**Comment by mayankshubham** [comment]
> ![Screenshot (3)](https://user-images.githubusercontent.com/51085756/113983904-1fa72300-9868-11eb-986b-17313b5d622c.png)
> 
> Just checked out your repos, good stuff. Thought of letting you know.

@prithvi60  This part of rendering cards is something I have to fix in this repo. It works directly in codesandbox demo and the article for which is  [published here](https://medium.com/codex/building-a-card-memory-game-in-react-e6400b226b8f).
